### ISSUE TITLE
Unit test failing: unit disparity in physchem.headloss_manifold

### ISSUE THREAD

**Issue by prevosis** [AguaClara/aide_design#18]
The test [`physchem.test_headloss_manifold_units`](https://github.com/AguaClara/aide_design/blob/bba5807914fb3c4243f215157dfece59c360df73/tests/test_physchem.py#L615) is failing; it seems to be a Pint error with the stack trace: 

```python
pint.errors.DimensionalityError: Cannot convert from 'centimeter ** 2 / second' ([length] ** 2 / [time]) to 'meter ** 3 / second' ([length] ** 3 / [time])
```

Error message makes sense to me but I'm not seeing where we pass in cm^2 / s. Also, it seems as if the internal functions called ([headloss_manifold](https://github.com/AguaClara/aide_design/blob/bba5807914fb3c4243f215157dfece59c360df73/aide_design/physchem.py#L362) , [headloss](https://github.com/AguaClara/aide_design/blob/bba5807914fb3c4243f215157dfece59c360df73/aide_design/physchem.py#L262), etc.) DO take m^2/s as input units. So I'm not sure where this cm^2/s error is coming from; perhaps someone is passing in a value with an incorrect unit. Can someone check this out?

**Comment by juanchon998** [comment]
There was an error in the headloss_manifold function which I had addressed with version 0.0.5: the first input (meant to be flowrate) was written to take units of u.m**2/u.s instead of its correct units of u.m**3/u.s. I adjusted this, but was not aware of the test function [physchem.test_headloss_manifold_units](https://github.com/AguaClara/aide_design/blob/bba5807914fb3c4243f215157dfece59c360df73/tests/test_physchem.py#L615) 
which was written with the same bug. Fixing the unit input in the test function should solve the problem.

**Comment by ethan92429** [comment]
@juanchon998 thanks! Already fixed 😄 but thanks anyways! This is a good reminder to always run tests when trying to fix something. Even small changes can have unexpected results.

**Comment by juanchon998** [comment]
I tested the function itself, but not the actual test function! My
apologies, thanks for the fix!

**Comment by ethan92429** [comment]
@juanchon998 no need to apologize. I think this probably comes from not knowing the proper test procedure. You can run all of the tests by, in the root of aide_design in your cmd/terminal, running `python setup.py test`.

**Comment by juanchon998** [comment]
I'll remember that did next time!

**Comment by prevosis** [comment]
Hmm, I'm still getting this test failing. My master branch is up-to-date as well. Can someone confirm that all the tests are passing?

**Comment by ethan92429** [comment]
The change is in 0.0.6 we never update master directly

El 15 nov. 2017 3:30 p.m., "Aadil Bhatti" <notifications@github.com>
escribió:

Hmm, I'm still getting this test failing. My master branch is up-to-date as
well. Can someone confirm that all the tests are passing?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/AguaClara/aide_design/issues/18#issuecomment-344734676>,
or mute the thread
