### ISSUE TITLE
Discrepancies between Mathcad code and python functions

### ISSUE THREAD

**Issue by zoemaisel** [AguaClara/aide_design#33]
@monroews @ethan92429 
Nominal diameter in pipe_database and area_orifices_top in LFOM are two functions that give different results in Mathcad vs python. 

Are these discrepancies an issue or if they are acceptable? We are writing test cases for LFOM code and have been comparing our calculations to Mathcad.

**Comment by ethan92429** [comment]
nominal pipe diameter gives different values because python calculates the thickness based on SDR and MathCAD uses tabulated values... it should be no more than 3% different. How large are the discrepancies you are seeing?

In what way do the two LFOM equations yield different results? what are some example params?

**Comment by fletchapin** [comment]
I'll have to check tomorrow on Mathcad what the output of the area of the orifices equation was in order to compare the two outpus.

For the nominal diameter equation, when a flow of 60 L/s and headloss of 20 cm are input the nominal diameter in Mathcad is 18 inches whereas in Python it's 16 inches. The calculation of the inner diameter is the same so the difference stems from the nominal diameter function in pipedatabase

**Comment by monroews** [comment]
This is likely because Mathcad pipe database doesn't include 16 inch pipes
and apparently the AIDE pipe database does include 18" pipes.

Cheers,


Monroe Weber-Shirk

AguaClara <http://aguaclara.cornell.edu/> at Cornell
Civil and Environmental Engineering <http://www.cee.cornell.edu/>
Cornell University <http://www.cornell.edu/>
Hollister Hall 265
(607) 216-8445
<http://aguaclara.cornell.edu/>

**Comment by zam7** [comment]
For area_lfom_orifices_top, the results are:

Python:  0.001317 m^2
Mathcad: 0.001778 m^2

This is a 26% difference assuming that Mathcad is the more accurate output.

**Comment by zam7** [comment]
@monroews We checked the pipe databases. Python does not include "Country Database" information. Mathcad indicates that Honduras does not have 16'' pipes so it chooses 18" but Python has only one database which doesn't distinguish between countries. 

Is this a problem? Do we need to include the country database information in Python?

**Comment by monroews** [comment]
## For orifice area of the top row.
Presumably the diameter of the drill was different for python and mathcad.
Thus the real question is whether the drill diameters are reasonable for fabrication.

##For country database
Country databases aren't a priority at this time. If needed an expert can edit the database for a particular country. Creating country databases could be something to add for a future release.

**Comment by zam7** [comment]
@monroews We checked; both Python and Mathcad are using the same drill series.

**Comment by monroews** [comment]
What is the Number of orifices per row for each of the designs?
Perhaps there is a difference in the logic used to get the number of
orifices in each row.
Perhaps the real question is how close is the flow to the theoretical value
for each design. If the flow is close (5%), then perhaps the change in
logic is okay.


Monroe Weber-Shirk

AguaClara <http://aguaclara.cornell.edu/> at Cornell
Civil and Environmental Engineering <http://www.cee.cornell.edu/>
Cornell University <http://www.cornell.edu/>
Hollister Hall 265
(607) 216-8445
<http://aguaclara.cornell.edu/>

**Comment by fletchapin** [comment]
We have added modifying this function to future work since the error is relatively small. This will also be tested more thoroughly once the workflow between Design, Template, and Draw is more fine-tuned.
